apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: europe-west1-docker.pkg.dev/qwiklabs-gcp-02-063a538c05c1/my-repo/hello:v2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"